version: "1.0"
name: birdsite
services:
  backend:
    build:
      context: .
      dockerfile: ./images/backend/Dockerfile
    volumes:
      - ./srv/backend:/srv/backend/
    ports:
      - '5000:5000'
    networks:
      - bird_site_network
  frontend:
    build:
      context: .
      dockerfile: ./images/frontend/Dockerfile
    volumes:
      - ./srv/frontend/bird-site:/srv/frontend/bird-site
    ports:
      - '3000:3000'
    tty: true
    deploy:
      resources:
        reservations:
          memory: 500M
    networks:
      - bird_site_network

networks:
  bird_site_network:
    driver: bridge